#!/usr/bin/env node
/**
 * Bundles data/*.json into assets/js/data.js.
 *
 * The site is plain static HTML that people should be able to open straight
 * from disk, and fetch() on a file:// URL is blocked by the browser, so the
 * data ships as a script that assigns window.HWD rather than as JSON the
 * pages request at runtime. Derived metrics are computed here, once, so the
 * pages never disagree about how a ratio was calculated.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const read = (p) => JSON.parse(readFileSync(join(root, p), 'utf8'));

const states = read('data/states.json');
const national = read('data/national.json');
const metrics = read('data/metrics.json');
const geo = read('data/geo.json');

const round = (n, d = 2) => Math.round(n * 10 ** d) / 10 ** d;
const gdpTotal = states.reduce((a, s) => a + s.gdp, 0);

for (const s of states) {
  s.gdpPerCapita = Math.round((s.gdp * 1e6) / s.pop);
  s.gdpShare = round((s.gdp / gdpTotal) * 100, 2);
  s.salesCombined = round(s.salesState + s.salesLocal, 2);
  s.mhiAdj = Math.round(s.mhi / (s.col / 100));
  s.priceToIncome = round(s.homeValue / s.mhi, 2);
  s.gdpGrowthNominal = round(((s.gdp - s.gdpPrev) / s.gdpPrev) * 100, 1);
  const g = geo.states[s.name];
  if (!g) throw new Error(`no geometry for ${s.name}`);
  s.path = g.d;
  s.centroid = g.c;
}

// Ranks for every numeric metric, so the UI never has to sort to rank.
const ranks = {};
for (const [key, def] of Object.entries(metrics.metrics)) {
  const desc = def.better !== 'low';
  const ordered = [...states]
    .filter((s) => typeof s[key] === 'number')
    .sort((a, b) => (desc ? b[key] - a[key] : a[key] - b[key]));
  ranks[key] = {};
  // Ties share a rank (competition ranking).
  let lastVal = null;
  let lastRank = 0;
  ordered.forEach((s, i) => {
    const rank = s[key] === lastVal ? lastRank : i + 1;
    ranks[key][s.abbr] = rank;
    lastVal = s[key];
    lastRank = rank;
  });
}

const bundle = {
  meta: {
    asOf: national.asOf,
    generated: new Date().toISOString().slice(0, 10),
    stateGdpSum: gdpTotal,
    nationalGdp: national.headline.gdp,
    residual: national.headline.gdp - gdpTotal,
  },
  states,
  national,
  metrics: metrics.metrics,
  groups: metrics.groups,
  sources: metrics.sources,
  ranks,
  nationPath: geo.nation,
};

const out = `/* Generated by scripts/build.mjs — edit data/*.json instead. */\nwindow.HWD = ${JSON.stringify(bundle)};\n`;
writeFileSync(join(root, 'assets/js/data.js'), out);

const kb = (n) => `${(n / 1024).toFixed(0)} KB`;
console.log(`assets/js/data.js written (${kb(out.length)})`);
console.log(`  states: ${states.length}`);
console.log(`  sum of state GDP: $${(gdpTotal / 1e6).toFixed(3)}T vs national $${(national.headline.gdp / 1e6).toFixed(3)}T`);
console.log(`  residual: $${(bundle.meta.residual / 1000).toFixed(0)}B`);
